apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rabbitmq
spec:
  host: rabbitmq-rabbit.apps-crc.testing
  port:
    targetPort: 15672
  to:
    kind: Service
    name: rabbitmq
    weight: 100
  wildcardPolicy: None