apiVersion: v1
data:
  default_user.conf: ZGVmYXVsdF91c2VyID0gZGVmYXVsdF91c2VyX2hHNzlTUDh1WkJJak9PMkRxaV8KZGVmYXVsdF9wYXNzID0genFfRkU2aWc1eG9XMFJfTXkxWDlJalJGY2tTQ2FUamEK
  host: aW1wb3J0LWRlZmluaXRpb25zLnJhYmJpdC5zdmM=
  password: enFfRkU2aWc1eG9XMFJfTXkxWDlJalJGY2tTQ2FUamE=
  port: NTY3Mg==
  provider: cmFiYml0bXE=
  type: cmFiYml0bXE=
  username: ZGVmYXVsdF91c2VyX2hHNzlTUDh1WkJJak9PMkRxaV8=
kind: Secret
metadata:
  annotations:
    rabbitmq.com/queueRebalanceNeededAt: "2024-09-22T14:39:52Z"
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: import-definitions
    app.kubernetes.io/part-of: rabbitmq
  name: import-definitions-default-user
type: Opaque
