apiVersion: v1
data:
  .erlang.cookie: UTJnaXVaWFB5RTF4RFE0TXhPUmNycWFaN3VELUl5Vnc=
kind: Secret
metadata:
  annotations:
    rabbitmq.com/queueRebalanceNeededAt: "2024-09-22T14:39:52Z"
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: import-definitions
    app.kubernetes.io/part-of: rabbitmq
  name: import-definitions-erlang-cookie
type: Opaque
