apiVersion: v1
data:
  operatorDefaults.conf: |
    queue_master_locator                       = min-masters
    disk_free_limit.absolute                   = 2GB
    cluster_partition_handling                 = pause_minority
    cluster_formation.peer_discovery_backend   = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host                 = kubernetes.default
    cluster_formation.k8s.address_type         = hostname
    cluster_formation.target_cluster_size_hint = 0
    cluster_name                               = import-definitions
    auth_mechanisms.1                          = PLAIN
    auth_mechanisms.2                          = AMQPLAIN
  userDefinedConfiguration.conf: |
    total_memory_available_override_value = 1717986919
    # Path to the mounted definitions file
    load_definitions                      = /etc/rabbitmq/definitions.json
kind: ConfigMap
metadata:
  annotations:
    rabbitmq.com/serverConfUpdatedAt: "2024-09-20T13:26:56Z"
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: import-definitions
    app.kubernetes.io/part-of: rabbitmq
  name: import-definitions-server-conf
